services:
  redis:
    image: redis:latest
    container_name: redis
    ports:
      - "6380:6379"
    networks:
       - bmc-net
  mongo:
    image: mongo:latest
    container_name: mongo
    ports:
      - "27018:27017"
    networks:
       - bmc-net
  sqlserver:
    image: mcr.microsoft.com/mssql/server:latest
    container_name: sqlserver
    environment:
        - ACCEPT_EULA=Y
        - SA_PASSWORD=KafEvent007
    ports:
      - "1433:1433"
    command:
      - /bin/bash
      - -c
      - |
        # Define the Google Drive file ID for the SQL script
        FILE_ID="1ATnHqnglHl85NXksk7dLu2Z3losM0OKu"  # Replace with your actual file ID
        DESTINATION="/tmp/script.sql"
        
        # Construct the Google Drive download URL
        URL="https://drive.usercontent.google.com/uc?id=${FILE_ID}&export=download"

        # Download the SQL script using wget (you can also use curl)
        #wget --no-check-certificate -O $DESTINATION "$URL"
        wget --no-check-certificate -O "$DESTINATION" "https://drive.google.com/uc?id=1ATnHqnglHl85NXksk7dLu2Z3losM0OKu&export=download"
        # Run the SQL script using sqlcmd
        /opt/mssql-tools/bin/sqlcmd -S localhost -U sa -P $SA_PASSWORD -i $DESTINATION

        # Finally, start SQL Server after the script runs
        /opt/mssql/bin/sqlservr
    networks:
       - bmc-net
  
  webadmin:
    image: bmc-digest
    container_name: webadmin
    build:
      context: .
      dockerfile: WebAdmin/Dockerfile
    ports:
      - "5001:5001"
    environment:
      ASPNETCORE_URLS: "http://0.0.0.0:5001"
      ASPNETCORE_ENVIRONMENT: "Production"
      REDIS_CONNECTION: "redis:6380"  # Redis service name and port
      MONGODB_CONNECTION: "mongo:27018"  # MongoDB connection string
      DB_CONNECTION_STRING: "Server=sqlserver,1433;Database=EventMGT;User Id=sa;Password=KafEvent007;"  # SQL Server connection string
    depends_on:
      - redis
      - mongo
      - sqlserver
    networks:
       - bmc-net

networks:
  bmc-net:
    driver: bridge
